{
 "title": "Sentinel Internal Operations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Open Incidents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sentinel_open_incidents" }
   ]
  },
  {
   "title": "Incident MTTR (Seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "sentinel_mttr_seconds" }
   ]
  },
  {
   "title": "Total Checks Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(sentinel_health_checks_total[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency Overview Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(sentinel_health_check_latency_ms_bucket[5m])) by (le)"
    }
   ]
  }
 ]
}